web:
  build: .
  ports:
    - "8080:80"
  volumes:
    - .:/srv/www
  links:
    - db
    - cache
db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD:
    MYSQL_DATABASE: monk
    MYSQL_USER: monk
    MYSQL_PASSWORD:
cache:
  image: memcached:latest
